version '2'

services:

  publication_stats_thriftserver:
    build: .
    restart: always
    ports:
      - "11620:11620"
      - "8000:8000"
    links:
      - org.scielo.citedby_thriftserver:org.scielo.citedby_thriftserver
      - org.scielo.cited_api:org.scielo.citedby_apidocker